language: go

go:
    - 1.7.x
    - 1.8.x
    - 1.9.x
    - 1.10.x
    - 1.11.x
    - tip

before_install:
  - export PATH=$HOME/gopath/bin:$PATH

script:
  - go test -race github.com/nlopes/slack/...
  - go test -cover github.com/nlopes/slack/...

matrix:
    allow_failures:
        - go: tip

git:
  depth: 10
